name: 'detectwaste/efficientdet-lighning'
exname: 'effdet-lighning'
gpus: 
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
grad_cval: 10
max_epoch: 50
opti_param:
  - lr: 0.001
  - opt: 'momentum'
  - opt-eps: 1e-3
  - momentum: 0.9
  - weight_decay: 4e-5
mod_name: 'tf_efficientdet_d2'
pre_train: True
pre_train_back: True